-- RETIRED: no executable SQL remains at this historical path.
-- Reference text: ../archive/floworder/sql/ordercare-incident-command-phase3.sql.txt
-- Do not execute the archived text for initialization, migration or cleanup.
