-- RETIRED: no executable SQL remains at this historical path.
-- Reference text: ../archive/floworder/sql/ordercare-incident-command-m1-b.sql.txt
-- Do not execute the archived text for initialization, migration or cleanup.
