-- HISTORICAL: this mixed schema included a retired domain table.
-- Reference text: ../archive/floworder/sql/unified-agent-workbench-m1-c.sql.txt
-- No executable SQL; not a current initialization or migration entry.
