package com.agent.platform.workbench.model;

/** M1 product-control events. Cross-source projection remains an M2 concern. */
public enum WorkEventType {
    WORK_ITEM_CREATED,
    ROUTING_STARTED,
    ROUTING_DECIDED,
    ROUTING_FAILED,
    CLARIFICATION_REQUIRED,
    ROUTE_CONFIRMATION_REQUIRED,
    DISPATCH_READY,
    DISPATCH_STARTED,
    DISPATCH_RECONCILED,
    EXECUTION_DISPATCHED,
    WORK_COMMAND_REQUESTED,
    WORK_COMMAND_REJECTED,
    WORK_COMMAND_FAILED,
    WORK_ITEM_PAUSE_REQUESTED,
    WORK_ITEM_PAUSED,
    WORK_ITEM_RESUMED,
    WORK_ITEM_CANCEL_REQUESTED,
    WORK_ITEM_CANCELLED,
    WORK_ITEM_ABANDONED,
    RUN_EVENT_PROJECTED,
    INCIDENT_EVENT_PROJECTED,
    RECOVERY_PLAN_EVENT_PROJECTED
}
