package com.agent.platform.ordercare.incident.model;

public enum TaskEventType {
    TASK_ASSIGNMENT,
    EVIDENCE_SUBMITTED,
    CLARIFICATION_REQUEST,
    CLARIFICATION_RESPONSE,
    EVIDENCE_CHALLENGE,
    TASK_CANCELLED,
    FINAL_RECOMMENDATION,
    INCIDENT_STATE_CHANGED,
    TASK_STATE_CHANGED,
    TASK_RETRY_SCHEDULED,
    TASK_LEASE_CLAIMED,
    TASK_LEASE_RECOVERED,
    EVIDENCE_CONFLICT_DETECTED,
    EVIDENCE_TRUST_ASSESSED,
    BUDGET_EXHAUSTED,
    IDEMPOTENCY_REJECTED,
    RECOVERY_PLAN_CHANGED
}
